# CI Workflow for tugboat

name: CI

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Lint (format check and vet)
        run: make lint

      - name: Run tests
        run: make test

      - name: Build binary
        env:
          CGO_ENABLED: "0"
        run: make build

      - name: Verify binary works
        run: ./tugboat version
